# Generated by Django 5.2.7 on 2025-10-21 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='headline',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='website',
        ),
    ]
