# Generated by Django 5.2.7 on 2025-10-21 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_candidateprofile_headline_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofile',
            old_name='name',
            new_name='company_name',
        ),
    ]
