# Generated by Django 5.2.6 on 2025-09-25 18:47

from django.db import migrations, models  # type:ignore


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vacante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("puesto", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                ("requisitos", models.TextField()),
                ("ubicacion", models.CharField(max_length=100)),
                ("salario", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "tipo_contrato",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("activa", models.BooleanField(default=True)),
            ],
        ),
    ]
