# Generated by Django 5.2.7 on 2025-10-14 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacante',
            old_name='salario',
            new_name='salariomax',
        ),
        migrations.AddField(
            model_name='vacante',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vacante',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacantes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vacante',
            name='departamento',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='vacante',
            name='salariomin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='puesto',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='requisitos',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='tipo_contrato',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='ubicacion',
            field=models.CharField(max_length=120),
        ),
    ]
