# Generated by Django 5.2.7 on 2025-10-21 00:05

from django.db import migrations, models  # type:ignore


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_rename_salario_vacante_salariomax_vacante_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacante",
            name="company_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Nombre de la empresa que publica la vacante",
                max_length=200,
            ),
        ),
    ]
