# Generated by Django 5.2.7 on 2025-10-28 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_vacante_company_name_alter_vacante_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('interview_config', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('active', 'Activa'), ('completed', 'Completada'), ('abandoned', 'Abandonada')], default='pending', max_length=20)),
                ('current_question_index', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('total_score', models.FloatField(default=0.0)),
                ('max_possible_score', models.FloatField(default=100.0)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview_session', to='jobs.application')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('candidate', 'Candidato'), ('ai', 'IA'), ('system', 'Sistema')], max_length=20)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('question_index', models.IntegerField(blank=True, null=True)),
                ('evaluation', models.JSONField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='jobs.interviewsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
