# Generated by Django 5.2.7 on 2025-10-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_interviewsession_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacante',
            name='generated_interview',
            field=models.JSONField(blank=True, help_text='Preguntas de entrevista generadas por IA', null=True),
        ),
    ]
