# Generated by Django 5.2.7 on 2025-11-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_vacante_generated_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
