# Generated by Django 5.2.8 on 2025-11-27 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_interviewsession_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='analysis_report',
            field=models.JSONField(blank=True, help_text='SWOT analysis report with quantitative score', null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='analyzed_at',
            field=models.DateTimeField(blank=True, help_text='When the analysis was generated', null=True),
        ),
    ]
